# Generated by Django 5.1.4 on 2025-12-21 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borlette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_borlette', models.CharField(max_length=150, unique=True)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=50)),
                ('logo_borlette', models.ImageField(blank=True, null=True, upload_to='borlettes/logos/')),
                ('slogan', models.CharField(max_length=255)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='borlette', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
