# Generated by Django 5.1.4 on 2025-12-21 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tirage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('JOUR', 'Jour'), ('SOIR', 'Soir'), ('SPECIAL', 'Spécial')], default='JOUR', max_length=16)),
                ('jours_actifs', models.JSONField(default=list)),
                ('heure_ouverture', models.TimeField()),
                ('heure_fermeture', models.TimeField()),
                ('heure_tirage', models.TimeField()),
                ('fermeture_auto', models.BooleanField(default=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=16)),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('resultat', models.TextField(blank=True, null=True)),
                ('date_resultat', models.DateField(blank=True, null=True)),
                ('borlette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tirages', to='accounts.borlette')),
            ],
        ),
    ]
