# Generated by Django 5.1.4 on 2025-12-21 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tirage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boule_1er_lot_coeff', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('boule_2eme_lot_coeff', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('boule_3eme_lot_coeff', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loto3_coeff', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loto4_coeff', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loto5_coeff', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mariage_normal_coeff', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mariage_gratuit_actif', models.BooleanField(default=False)),
                ('mariage_gratuit_seuil1', models.PositiveIntegerField(default=4)),
                ('mariage_gratuit_qty1', models.PositiveIntegerField(default=3)),
                ('mariage_gratuit_seuil2', models.PositiveIntegerField(default=10)),
                ('mariage_gratuit_qty2', models.PositiveIntegerField(default=6)),
                ('mariage_gratuit_montant_fixe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borlette', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='accounts.borlette')),
            ],
        ),
    ]
