# Generated by Django 5.1.4 on 2026-02-01 12:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tiragecombisstats_bloque_derived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lot1', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$', message='lot doit être au format 00 à 99')])),
                ('lot2', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$', message='lot doit être au format 00 à 99')])),
                ('lot3', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$', message='lot doit être au format 00 à 99')])),
                ('chiffre_loto3', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^\\d$', message='chiffre doit être 0 à 9')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tirage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='accounts.tirage')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tirage', 'date'), name='uniq_tirage_date_resultat')],
            },
        ),
    ]
