# Generated by Django 5.1.4 on 2026-02-01 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_default_expense_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpayout',
            name='borlette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_payouts', to='accounts.borlette'),
        ),
        migrations.AddField(
            model_name='agentpayout',
            name='snapshot_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentpayout',
            name='snapshot_period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
