# Generated by Django 5.1.4 on 2026-02-02 09:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='borlette',
            name='allow_offline_print',
            field=models.BooleanField(default=False, help_text='Allow agents to print offline tickets (HL-XXXXXXXX)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('TICKET_CREATE', 'Ticket Create'), ('TICKET_VOID', 'Ticket Void'), ('TICKET_PAYOUT', 'Ticket Payout'), ('RESULTS_SET', 'Results Set'), ('RESULTS_RESET', 'Results Reset'), ('RISK_BLOCK_ADD', 'Risk Block Add'), ('RISK_BLOCK_REMOVE', 'Risk Block Remove'), ('AGENT_COMMISSION_PAYOUT', 'Agent Commission Payout'), ('EXPENSE_CREATE', 'Expense Create'), ('EXPENSE_UPDATE', 'Expense Update'), ('EXPENSE_DELETE', 'Expense Delete'), ('LOGIN_ADMIN', 'Login Admin'), ('LOGIN_AGENT', 'Login Agent'), ('DEVICE_REGISTER', 'Device Register'), ('OFFLINE_TICKET_QUEUED', 'Offline Ticket Queued'), ('OFFLINE_SYNC_SUCCESS', 'Offline Sync Success'), ('OFFLINE_SYNC_FAILED', 'Offline Sync Failed'), ('OFFLINE_TAMPER_BLOCKED', 'Offline Tamper Blocked'), ('OFFLINE_BATCH_PARTIAL', 'Offline Batch Partial')], max_length=64),
        ),
        migrations.AlterField(
            model_name='tirage',
            name='cached_state',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.CreateModel(
            name='AgentDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('device_secret', models.CharField(max_length=128)),
                ('device_name', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.agent')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'is_active'], name='idx_device_agent_active')],
            },
        ),
        migrations.CreateModel(
            name='MariageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boule_a', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('boule_b', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mariage_blocks_created', to=settings.AUTH_USER_MODEL)),
                ('tirage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mariage_blocks', to='accounts.tirage')),
            ],
            options={
                'ordering': ['boule_a', 'boule_b'],
                'indexes': [models.Index(fields=['tirage', 'boule_a', 'boule_b'], name='idx_mariage_block_lookup')],
                'constraints': [models.UniqueConstraint(fields=('tirage', 'boule_a', 'boule_b'), name='uniq_tirage_mariage_block')],
            },
        ),
    ]
