# Generated by Django 5.1.4 on 2026-02-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_borlette_offline_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='tirage',
            name='mariage_automatique',
            field=models.BooleanField(default=False, help_text='Activer les mariages automatiques pour ce tirage'),
        ),
    ]
