# Generated by Django 5.0.14 on 2026-04-16 01:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_userrole_affiliate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_percent', models.IntegerField(default=20, help_text='Commission en pourcentage')),
                ('total_referrals', models.PositiveIntegerField(default=0)),
                ('active_referrals', models.PositiveIntegerField(default=0)),
                ('can_submit_results', models.BooleanField(default=False, help_text="Permet à l'affilié de soumettre les résultats des tirages par défaut")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='resultat',
            name='uniq_resultat_tirage_date',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='idx_expense_borlette_dt',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='idx_expense_cat',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='tirage',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('TICKET_CREATE', 'Ticket Create'), ('TICKET_VOID', 'Ticket Void'), ('TICKET_PAYOUT', 'Ticket Payout'), ('RESULTS_SET', 'Results Set'), ('RESULTS_RESET', 'Results Reset'), ('RESULTS_VALIDATE', 'Results Validate'), ('RESULTS_REJECT', 'Results Reject'), ('RESULTS_PENDING', 'Results Pending'), ('RESULTS_FLAG', 'Results Flag'), ('STAFF_CREATE', 'Staff Create'), ('STAFF_UPDATE', 'Staff Update'), ('STAFF_TOGGLE_ACTIVE', 'Staff Toggle Active'), ('RESULTS_EDIT', 'Results Edit'), ('RISK_BLOCK_ADD', 'Risk Block Add'), ('RISK_BLOCK_REMOVE', 'Risk Block Remove'), ('AGENT_COMMISSION_PAYOUT', 'Agent Commission Payout'), ('EXPENSE_CREATE', 'Expense Create'), ('EXPENSE_UPDATE', 'Expense Update'), ('EXPENSE_DELETE', 'Expense Delete'), ('LOGIN_ADMIN', 'Login Admin'), ('LOGIN_AGENT', 'Login Agent'), ('BORLETTE_UPDATE', 'Borlette Update'), ('FINANCIAL_DISTRIBUTION_CALC', 'Financial Distribution Calc'), ('WITHDRAWAL_CREATE', 'Withdrawal Create'), ('WITHDRAWAL_APPROVE', 'Withdrawal Approve'), ('WITHDRAWAL_REJECT', 'Withdrawal Reject'), ('WITHDRAWAL_MARK_PAID', 'Withdrawal Mark Paid'), ('DEVICE_REGISTER', 'Device Register'), ('OFFLINE_TICKET_QUEUED', 'Offline Ticket Queued'), ('OFFLINE_SYNC_SUCCESS', 'Offline Sync Success'), ('OFFLINE_SYNC_FAILED', 'Offline Sync Failed'), ('OFFLINE_TAMPER_BLOCKED', 'Offline Tamper Blocked'), ('OFFLINE_BATCH_PARTIAL', 'Offline Batch Partial')], max_length=64),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='complementaire',
            field=models.CharField(blank=True, default='', max_length=1, validators=[django.core.validators.RegexValidator('^\\d$', message='chiffre doit être 0 à 9')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('AGENT', 'Agent'), ('AFFILIATE', 'Affiliate')], default='ADMIN', max_length=32),
        ),
        migrations.AddField(
            model_name='affiliateprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='affiliateprofile',
            index=models.Index(fields=['promo_code'], name='idx_aff_promo'),
        ),
        migrations.AddIndex(
            model_name='affiliateprofile',
            index=models.Index(fields=['user'], name='idx_aff_user'),
        ),
        migrations.AddIndex(
            model_name='affiliateprofile',
            index=models.Index(fields=['is_active'], name='idx_aff_active'),
        ),
    ]
