# Generated by Django 5.0.14 on 2026-04-16 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_add_affiliate_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateprofile',
            name='payment_full_name',
            field=models.CharField(blank=True, help_text='Nom complet pour Western Union', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='affiliateprofile',
            name='payment_location',
            field=models.CharField(blank=True, help_text='Ville/Localisation pour Western Union', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='affiliateprofile',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('moncash', 'MonCash'), ('natcash', 'NatCash'), ('western_union', 'Western Union')], help_text='Méthode de paiement préférée', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='affiliateprofile',
            name='payment_phone',
            field=models.CharField(blank=True, help_text='Numéro pour MonCash/NatCash', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='admin_notes',
            field=models.TextField(blank=True, default='', help_text="Notes de l'administrateur"),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='expected_by',
            field=models.DateTimeField(blank=True, help_text='Date limite de traitement (48h)', null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payment_full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payment_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payment_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='proof_screenshot',
            field=models.ImageField(blank=True, help_text='Screenshot de preuve de paiement', null=True, upload_to='withdrawal_proofs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('moncash', 'MonCash'), ('natcash', 'NatCash'), ('western_union', 'Western Union')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['expected_by'], name='idx_withdraw_expected'),
        ),
    ]
