# Generated by Django 5.0.14 on 2026-04-18 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_user_role_partnerprofile_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='loto4_option1',
            field=models.CharField(blank=True, default='', help_text='1ère option Loto4', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', message='Loto4 doit être 4 chiffres')]),
        ),
        migrations.AddField(
            model_name='resultat',
            name='loto4_option2',
            field=models.CharField(blank=True, default='', help_text='2ème option Loto4', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', message='Loto4 doit être 4 chiffres')]),
        ),
        migrations.AddField(
            model_name='resultat',
            name='loto4_option3',
            field=models.CharField(blank=True, default='', help_text='3ème option Loto4', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', message='Loto4 doit être 4 chiffres')]),
        ),
        migrations.AddField(
            model_name='resultat',
            name='loto5_option1',
            field=models.CharField(blank=True, default='', help_text='1ère option Loto5', max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', message='Loto5 doit être 5 chiffres')]),
        ),
        migrations.AddField(
            model_name='resultat',
            name='loto5_option2',
            field=models.CharField(blank=True, default='', help_text='2ème option Loto5', max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', message='Loto5 doit être 5 chiffres')]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('trial', 'Essai Gratuit'), ('standard', 'Standard'), ('premium', 'Premium')], default='standard', help_text="Type d'abonnement", max_length=50),
        ),
    ]
