# Generated by Django 5.0.14 on 2026-04-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_resultat_loto4_option1_resultat_loto4_option2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_proof',
            field=models.FileField(blank=True, help_text="Preuve de paiement (capture d'écran, reçu, etc.)", null=True, upload_to='payment_proofs/%Y/%m/', verbose_name='Preuve de paiement'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_proof_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
