# Generated by Django 5.0.14 on 2026-04-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_subscription_payment_proof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la vidéo')),
                ('youtube_url', models.URLField(verbose_name='URL YouTube')),
                ('youtube_video_id', models.CharField(max_length=50, verbose_name='ID de la vidéo YouTube')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Catégorie')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vidéo de documentation',
                'verbose_name_plural': 'Vidéos de documentation',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
