# Generated by Django 5.0.14 on 2026-04-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_documentationvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='borlette',
            name='mariage_gratuit_actif',
            field=models.BooleanField(default=False, help_text='Activer le mariage gratuit pour cette borlette'),
        ),
        migrations.AddField(
            model_name='borlette',
            name='mariage_gratuit_montant',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant fixe du mariage gratuit en Gourdes', max_digits=10),
        ),
        migrations.AddField(
            model_name='borlette',
            name='ticket_footer_text',
            field=models.TextField(blank=True, default='La fiche est payable une seule fois au porteur. Le montant gagné devra être réclamé avant 90 jours', help_text='Texte de pied de page modifiable pour les tickets'),
        ),
    ]
