# Generated by Django 5.0.14 on 2026-04-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_borlette_mariage_gratuit_actif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('TICKET_CREATE', 'Ticket Create'), ('TICKET_VOID', 'Ticket Void'), ('TICKET_PAYOUT', 'Ticket Payout'), ('RESULTS_SET', 'Results Set'), ('RESULTS_RESET', 'Results Reset'), ('RESULTS_VALIDATE', 'Results Validate'), ('RESULTS_REJECT', 'Results Reject'), ('RESULTS_PENDING', 'Results Pending'), ('RESULTS_FLAG', 'Results Flag'), ('STAFF_CREATE', 'Staff Create'), ('STAFF_UPDATE', 'Staff Update'), ('STAFF_TOGGLE_ACTIVE', 'Staff Toggle Active'), ('RESULTS_EDIT', 'Results Edit'), ('RISK_BLOCK_ADD', 'Risk Block Add'), ('RISK_BLOCK_REMOVE', 'Risk Block Remove'), ('AGENT_COMMISSION_PAYOUT', 'Agent Commission Payout'), ('AGENT_CASHBOX_WITHDRAWAL', 'Agent Cashbox Withdrawal'), ('EXPENSE_CREATE', 'Expense Create'), ('EXPENSE_UPDATE', 'Expense Update'), ('EXPENSE_DELETE', 'Expense Delete'), ('LOGIN_ADMIN', 'Login Admin'), ('LOGIN_AGENT', 'Login Agent'), ('BORLETTE_UPDATE', 'Borlette Update'), ('FINANCIAL_DISTRIBUTION_CALC', 'Financial Distribution Calc'), ('WITHDRAWAL_CREATE', 'Withdrawal Create'), ('WITHDRAWAL_APPROVE', 'Withdrawal Approve'), ('WITHDRAWAL_REJECT', 'Withdrawal Reject'), ('WITHDRAWAL_MARK_PAID', 'Withdrawal Mark Paid'), ('DEVICE_REGISTER', 'Device Register'), ('OFFLINE_TICKET_QUEUED', 'Offline Ticket Queued'), ('OFFLINE_SYNC_SUCCESS', 'Offline Sync Success'), ('OFFLINE_SYNC_FAILED', 'Offline Sync Failed'), ('OFFLINE_TAMPER_BLOCKED', 'Offline Tamper Blocked'), ('OFFLINE_BATCH_PARTIAL', 'Offline Batch Partial')], max_length=64),
        ),
    ]
