# Generated by Django 5.0.14 on 2026-05-03 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTiragePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tirage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_preferences', to='accounts.tirage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tirage_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'tirage'], name='idx_admin_tirage'), models.Index(fields=['user', 'actif'], name='idx_admin_actif')],
            },
        ),
        migrations.AddConstraint(
            model_name='admintiragepreference',
            constraint=models.UniqueConstraint(fields=('user', 'tirage'), name='uniq_admin_tirage_pref'),
        ),
    ]
