# Generated by Django 5.0.14 on 2026-05-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_admintiragepreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tirage',
            name='heure_fermeture',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tirage',
            name='heure_ouverture',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tirage',
            name='heure_tirage',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
