# Generated by Django 5.0.14 on 2026-05-09 10:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def update_zero_limits_to_50000(apps, schema_editor):
    AdminPaymentSettings = apps.get_model("accounts", "AdminPaymentSettings")
    for s in AdminPaymentSettings.objects.all():
        changed = False
        if s.max_boule == Decimal("0"):
            s.max_boule = Decimal("50000")
            changed = True
        if s.max_loto3 == Decimal("0"):
            s.max_loto3 = Decimal("50000")
            changed = True
        if s.max_loto4 == Decimal("0"):
            s.max_loto4 = Decimal("50000")
            changed = True
        if s.max_loto5 == Decimal("0"):
            s.max_loto5 = Decimal("50000")
            changed = True
        if s.max_mariage == Decimal("0"):
            s.max_mariage = Decimal("50000")
            changed = True
        if changed:
            s.save(update_fields=["max_boule", "max_loto3", "max_loto4", "max_loto5", "max_mariage"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_tirage_heure_fermeture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpaymentsettings',
            name='max_boule',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='adminpaymentsettings',
            name='max_loto3',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='adminpaymentsettings',
            name='max_loto4',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='adminpaymentsettings',
            name='max_loto5',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='adminpaymentsettings',
            name='max_mariage',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RunPython(update_zero_limits_to_50000),
    ]
