# Generated by Django 5.0.14 on 2026-05-11 06:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_increase_default_max_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text="Force l'utilisateur à changer son mot de passe à la prochaine connexion"),
        ),
        migrations.CreateModel(
            name='AccountRecoveryRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RESOLVED', 'Résolu'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=16)),
                ('phone_number', models.CharField(blank=True, help_text='Numéro de téléphone de vérification', max_length=50)),
                ('message', models.TextField(blank=True, help_text='Message du client')),
                ('temp_password', models.CharField(blank=True, help_text='Mot de passe temporaire généré par le superadmin', max_length=128, null=True)),
                ('temp_password_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('borlette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_requests', to='accounts.borlette')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_recoveries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_recovery_status_ca'), models.Index(fields=['user'], name='idx_recovery_user')],
            },
        ),
    ]
