# Generated by Django 5.0.14 on 2026-06-23 06:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_add_recovery_and_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_public_key', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_secret_key', models.CharField(blank=True, default='', max_length=255)),
                ('moncash_client_id', models.CharField(blank=True, default='', max_length=255)),
                ('moncash_secret_key', models.CharField(blank=True, default='', max_length=255)),
                ('moncash_sandbox', models.BooleanField(default=True)),
                ('automatic_payments_active', models.BooleanField(default=False)),
                ('stripe_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('3.5'), max_digits=5)),
                ('stripe_fee_fixed', models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=5)),
                ('moncash_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5)),
                ('moncash_fee_fixed', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Globale Paiement',
                'verbose_name_plural': 'Configurations Globales Paiement',
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='last_location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='active_session_id',
            field=models.CharField(blank=True, help_text="Identifiant de la session active de l'agent pour restreindre à un seul appareil", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('trial', 'Essai Gratuit'), ('standard', 'Standard'), ('premium', 'Premium'), ('mensuel', 'Mensuel')], default='standard', help_text="Type d'abonnement", max_length=50),
        ),
    ]
