# Generated by Django 5.0.14 on 2026-06-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_globalpaymentsettings_agent_last_location_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_signature',
            field=models.CharField(blank=True, help_text="Signature de l'appareil de l'agent", max_length=255, null=True),
        ),
    ]
