# Generated by Django 5.0.14 on 2026-06-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_smtpsettings_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borlette',
            name='logo_base64',
            field=models.TextField(blank=True, help_text='Version base64 persistante du logo', null=True),
        ),
    ]
