# Generated by Django 5.0.14 on 2026-06-28 03:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_borlette_logo_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpaymentsettings',
            name='boule_1er_lot_coeff',
            field=models.DecimalField(decimal_places=2, default=Decimal('60'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='adminpaymentsettings',
            name='boule_2eme_lot_coeff',
            field=models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='adminpaymentsettings',
            name='boule_3eme_lot_coeff',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='adminpaymentsettings',
            name='loto3_coeff',
            field=models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='adminpaymentsettings',
            name='loto4_coeff',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='adminpaymentsettings',
            name='loto5_coeff',
            field=models.DecimalField(decimal_places=2, default=Decimal('25000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='adminpaymentsettings',
            name='mariage_gratuit_montant_fixe',
            field=models.DecimalField(decimal_places=2, default=Decimal('500'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='adminpaymentsettings',
            name='mariage_normal_coeff',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000'), max_digits=10),
        ),
    ]
