// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: validator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TicketPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketUuid    string                 `protobuf:"bytes,1,opt,name=ticket_uuid,json=ticketUuid,proto3" json:"ticket_uuid,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	BorletteId    string                 `protobuf:"bytes,3,opt,name=borlette_id,json=borletteId,proto3" json:"borlette_id,omitempty"`
	TirageIds     []string               `protobuf:"bytes,4,rep,name=tirage_ids,json=tirageIds,proto3" json:"tirage_ids,omitempty"`
	Lines         []*TicketLine          `protobuf:"bytes,5,rep,name=lines,proto3" json:"lines,omitempty"`
	TotalMise     float64                `protobuf:"fixed64,6,opt,name=total_mise,json=totalMise,proto3" json:"total_mise,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SessionKey    string                 `protobuf:"bytes,8,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketPayload) Reset() {
	*x = TicketPayload{}
	mi := &file_validator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketPayload) ProtoMessage() {}

func (x *TicketPayload) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketPayload.ProtoReflect.Descriptor instead.
func (*TicketPayload) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{0}
}

func (x *TicketPayload) GetTicketUuid() string {
	if x != nil {
		return x.TicketUuid
	}
	return ""
}

func (x *TicketPayload) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TicketPayload) GetBorletteId() string {
	if x != nil {
		return x.BorletteId
	}
	return ""
}

func (x *TicketPayload) GetTirageIds() []string {
	if x != nil {
		return x.TirageIds
	}
	return nil
}

func (x *TicketPayload) GetLines() []*TicketLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *TicketPayload) GetTotalMise() float64 {
	if x != nil {
		return x.TotalMise
	}
	return 0
}

func (x *TicketPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TicketPayload) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

type TicketLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameType      string                 `protobuf:"bytes,1,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	Numbers       string                 `protobuf:"bytes,2,opt,name=numbers,proto3" json:"numbers,omitempty"`
	Mise          float64                `protobuf:"fixed64,3,opt,name=mise,proto3" json:"mise,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketLine) Reset() {
	*x = TicketLine{}
	mi := &file_validator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketLine) ProtoMessage() {}

func (x *TicketLine) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketLine.ProtoReflect.Descriptor instead.
func (*TicketLine) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{1}
}

func (x *TicketLine) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *TicketLine) GetNumbers() string {
	if x != nil {
		return x.Numbers
	}
	return ""
}

func (x *TicketLine) GetMise() float64 {
	if x != nil {
		return x.Mise
	}
	return 0
}

type SignTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *TicketPayload         `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignTicketRequest) Reset() {
	*x = SignTicketRequest{}
	mi := &file_validator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTicketRequest) ProtoMessage() {}

func (x *SignTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTicketRequest.ProtoReflect.Descriptor instead.
func (*SignTicketRequest) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{2}
}

func (x *SignTicketRequest) GetPayload() *TicketPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SignTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	TicketUuid    string                 `protobuf:"bytes,2,opt,name=ticket_uuid,json=ticketUuid,proto3" json:"ticket_uuid,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignTicketResponse) Reset() {
	*x = SignTicketResponse{}
	mi := &file_validator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTicketResponse) ProtoMessage() {}

func (x *SignTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTicketResponse.ProtoReflect.Descriptor instead.
func (*SignTicketResponse) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{3}
}

func (x *SignTicketResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SignTicketResponse) GetTicketUuid() string {
	if x != nil {
		return x.TicketUuid
	}
	return ""
}

func (x *SignTicketResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SignTicketResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VerifyTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *TicketPayload         `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTicketRequest) Reset() {
	*x = VerifyTicketRequest{}
	mi := &file_validator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTicketRequest) ProtoMessage() {}

func (x *VerifyTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTicketRequest.ProtoReflect.Descriptor instead.
func (*VerifyTicketRequest) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyTicketRequest) GetPayload() *TicketPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *VerifyTicketRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type VerifyTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	TicketUuid    string                 `protobuf:"bytes,2,opt,name=ticket_uuid,json=ticketUuid,proto3" json:"ticket_uuid,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTicketResponse) Reset() {
	*x = VerifyTicketResponse{}
	mi := &file_validator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTicketResponse) ProtoMessage() {}

func (x *VerifyTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTicketResponse.ProtoReflect.Descriptor instead.
func (*VerifyTicketResponse) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyTicketResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyTicketResponse) GetTicketUuid() string {
	if x != nil {
		return x.TicketUuid
	}
	return ""
}

func (x *VerifyTicketResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_validator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_validator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_validator_proto protoreflect.FileDescriptor

const file_validator_proto_rawDesc = "" +
	"\n" +
	"\x0fvalidator.proto\x12\tvalidator\"\x96\x02\n" +
	"\rTicketPayload\x12\x1f\n" +
	"\vticket_uuid\x18\x01 \x01(\tR\n" +
	"ticketUuid\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1f\n" +
	"\vborlette_id\x18\x03 \x01(\tR\n" +
	"borletteId\x12\x1d\n" +
	"\n" +
	"tirage_ids\x18\x04 \x03(\tR\ttirageIds\x12+\n" +
	"\x05lines\x18\x05 \x03(\v2\x15.validator.TicketLineR\x05lines\x12\x1d\n" +
	"\n" +
	"total_mise\x18\x06 \x01(\x01R\ttotalMise\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vsession_key\x18\b \x01(\tR\n" +
	"sessionKey\"W\n" +
	"\n" +
	"TicketLine\x12\x1b\n" +
	"\tgame_type\x18\x01 \x01(\tR\bgameType\x12\x18\n" +
	"\anumbers\x18\x02 \x01(\tR\anumbers\x12\x12\n" +
	"\x04mise\x18\x03 \x01(\x01R\x04mise\"G\n" +
	"\x11SignTicketRequest\x122\n" +
	"\apayload\x18\x01 \x01(\v2\x18.validator.TicketPayloadR\apayload\"\x83\x01\n" +
	"\x12SignTicketResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12\x1f\n" +
	"\vticket_uuid\x18\x02 \x01(\tR\n" +
	"ticketUuid\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"g\n" +
	"\x13VerifyTicketRequest\x122\n" +
	"\apayload\x18\x01 \x01(\v2\x18.validator.TicketPayloadR\apayload\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\"c\n" +
	"\x14VerifyTicketResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1f\n" +
	"\vticket_uuid\x18\x02 \x01(\tR\n" +
	"ticketUuid\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xeb\x01\n" +
	"\tValidator\x12I\n" +
	"\n" +
	"SignTicket\x12\x1c.validator.SignTicketRequest\x1a\x1d.validator.SignTicketResponse\x12O\n" +
	"\fVerifyTicket\x12\x1e.validator.VerifyTicketRequest\x1a\x1f.validator.VerifyTicketResponse\x12B\n" +
	"\vHealthCheck\x12\x18.validator.HealthRequest\x1a\x19.validator.HealthResponseB\x12Z\x10gateway_go/protob\x06proto3"

var (
	file_validator_proto_rawDescOnce sync.Once
	file_validator_proto_rawDescData []byte
)

func file_validator_proto_rawDescGZIP() []byte {
	file_validator_proto_rawDescOnce.Do(func() {
		file_validator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_validator_proto_rawDesc), len(file_validator_proto_rawDesc)))
	})
	return file_validator_proto_rawDescData
}

var file_validator_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_validator_proto_goTypes = []any{
	(*TicketPayload)(nil),        // 0: validator.TicketPayload
	(*TicketLine)(nil),           // 1: validator.TicketLine
	(*SignTicketRequest)(nil),    // 2: validator.SignTicketRequest
	(*SignTicketResponse)(nil),   // 3: validator.SignTicketResponse
	(*VerifyTicketRequest)(nil),  // 4: validator.VerifyTicketRequest
	(*VerifyTicketResponse)(nil), // 5: validator.VerifyTicketResponse
	(*HealthRequest)(nil),        // 6: validator.HealthRequest
	(*HealthResponse)(nil),       // 7: validator.HealthResponse
}
var file_validator_proto_depIdxs = []int32{
	1, // 0: validator.TicketPayload.lines:type_name -> validator.TicketLine
	0, // 1: validator.SignTicketRequest.payload:type_name -> validator.TicketPayload
	0, // 2: validator.VerifyTicketRequest.payload:type_name -> validator.TicketPayload
	2, // 3: validator.Validator.SignTicket:input_type -> validator.SignTicketRequest
	4, // 4: validator.Validator.VerifyTicket:input_type -> validator.VerifyTicketRequest
	6, // 5: validator.Validator.HealthCheck:input_type -> validator.HealthRequest
	3, // 6: validator.Validator.SignTicket:output_type -> validator.SignTicketResponse
	5, // 7: validator.Validator.VerifyTicket:output_type -> validator.VerifyTicketResponse
	7, // 8: validator.Validator.HealthCheck:output_type -> validator.HealthResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_validator_proto_init() }
func file_validator_proto_init() {
	if File_validator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_validator_proto_rawDesc), len(file_validator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_validator_proto_goTypes,
		DependencyIndexes: file_validator_proto_depIdxs,
		MessageInfos:      file_validator_proto_msgTypes,
	}.Build()
	File_validator_proto = out.File
	file_validator_proto_goTypes = nil
	file_validator_proto_depIdxs = nil
}
