# Generated by Django 5.1.4 on 2026-02-04 08:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0018_tirage_mariage_automatique'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('PAYOUT', 'Paiement gain'), ('ALERT', 'Alerte'), ('INFO', 'Information'), ('RESULT', 'Résultat saisi')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borlette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to='accounts.borlette')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['borlette', 'is_read', '-created_at'], name='idx_notif_bor_read_dt'), models.Index(fields=['borlette', 'notification_type'], name='idx_notif_bor_type')],
            },
        ),
    ]
