# Generated by Django 5.1.4 on 2026-02-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('PAYOUT', 'Paiement gain'), ('COMMISSION_WITHDRAW', 'Retrait commission'), ('ALERT', 'Alerte'), ('INFO', 'Information'), ('RESULT', 'Résultat saisi')], max_length=20),
        ),
    ]
