# Generated by Django 5.1.4 on 2025-12-22 00:53

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_tirage_risk_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_ticket', models.CharField(db_index=True, max_length=40)),
                ('total_mise', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gain_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='VALIDE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.agent')),
                ('borlette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.borlette')),
            ],
        ),
        migrations.CreateModel(
            name='TicketLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeu', models.CharField(max_length=16)),
                ('valeur', models.CharField(max_length=10)),
                ('mise', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='agent_portal.ticket')),
            ],
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['borlette', 'agent', 'created_at'], name='idx_ticket_agent_dt'),
        ),
        migrations.AddIndex(
            model_name='ticketline',
            index=models.Index(fields=['ticket', 'jeu'], name='idx_tline_ticket_jeu'),
        ),
    ]
