# Generated by Django 5.1.4 on 2026-01-31 12:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tiragecombisstats_bloque_derived'),
        ('agent_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='gain_total',
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tirages',
            field=models.ManyToManyField(related_name='tickets', to='accounts.tirage'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_gain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ticketline',
            name='gratuit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketline',
            name='potentiel_gain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='statut',
            field=models.CharField(choices=[('PREVIEW', 'Preview'), ('VALIDE', 'Validé'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé')], default='PREVIEW', max_length=16),
        ),
        migrations.AlterField(
            model_name='ticketline',
            name='valeur',
            field=models.CharField(max_length=12),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['borlette', 'statut'], name='idx_ticket_borlette_statut'),
        ),
    ]
