# Generated by Django 5.1.4 on 2026-02-01 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_resultat'),
        ('agent_portal', '0002_ticket_uuid_enhanced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='tirages',
        ),
        migrations.AddField(
            model_name='ticket',
            name='group_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tirage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.tirage'),
        ),
    ]
