# Generated by Django 5.1.4 on 2026-02-01 21:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_agent_payout_updates'),
        ('agent_portal', '0004_session_based_results'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('COMMISSION_EARNED', 'Commission gagnée'), ('COMMISSION_PAYOUT', 'Paiement commission'), ('EXPENSE', 'Dépense'), ('ADJUSTMENT', 'Ajustement')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period_key', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='accounts.agent')),
                ('borlette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_ledger_entries', to='accounts.borlette')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_ledger_entries_created', to=settings.AUTH_USER_MODEL)),
                ('related_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='agent_portal.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'created_at'], name='idx_ledger_agent_dt'), models.Index(fields=['agent', 'entry_type'], name='idx_ledger_agent_type'), models.Index(fields=['borlette', 'created_at'], name='idx_ledger_borlette_dt')],
            },
        ),
    ]
