# Generated by Django 5.1.4 on 2026-02-01 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_agent_payout_updates'),
        ('agent_portal', '0005_agent_ledger_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agentledgerentry',
            index=models.Index(fields=['borlette', 'agent', 'created_at'], name='idx_ledger_bor_agent_dt'),
        ),
        migrations.AddIndex(
            model_name='agentledgerentry',
            index=models.Index(fields=['borlette', 'entry_type', 'created_at'], name='idx_ledger_bor_type_dt'),
        ),
        migrations.AddConstraint(
            model_name='agentledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'COMMISSION_EARNED')), fields=('related_ticket', 'entry_type'), name='uniq_commission_per_ticket'),
        ),
    ]
