# Generated by Django 5.1.4 on 2026-02-01 22:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_agent_payout_updates'),
        ('agent_portal', '0006_ledger_constraints_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_gain_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='TicketPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_payouts', to='accounts.agent')),
                ('borlette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_payouts', to='accounts.borlette')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_payouts_created', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='agent_portal.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentCashboxEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('SALE_CASH_IN', 'Vente (encaissement)'), ('WIN_PAYOUT_CASH_OUT', 'Paiement gain (décaissement)'), ('ADJUSTMENT', 'Ajustement')], max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period_key', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashbox_entries', to='accounts.agent')),
                ('borlette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_cashbox_entries', to='accounts.borlette')),
                ('related_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbox_entries', to='agent_portal.ticket')),
                ('related_payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbox_entries', to='agent_portal.ticketpayout')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticketpayout',
            index=models.Index(fields=['agent', 'created_at'], name='idx_tpayout_agent_dt'),
        ),
        migrations.AddIndex(
            model_name='ticketpayout',
            index=models.Index(fields=['borlette', 'created_at'], name='idx_tpayout_bor_dt'),
        ),
        migrations.AddIndex(
            model_name='agentcashboxentry',
            index=models.Index(fields=['agent', 'created_at'], name='idx_cashbox_agent_dt'),
        ),
        migrations.AddIndex(
            model_name='agentcashboxentry',
            index=models.Index(fields=['borlette', 'created_at'], name='idx_cashbox_bor_dt'),
        ),
        migrations.AddIndex(
            model_name='agentcashboxentry',
            index=models.Index(fields=['borlette', 'agent', 'entry_type'], name='idx_cashbox_bor_ag_type'),
        ),
        migrations.AddConstraint(
            model_name='agentcashboxentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'SALE_CASH_IN')), fields=('related_ticket', 'entry_type'), name='uniq_cashbox_sale_per_ticket'),
        ),
    ]
