# Generated by Django 5.0.14 on 2026-04-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_portal', '0008_alter_agentcashboxentry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcashboxentry',
            name='entry_type',
            field=models.CharField(choices=[('SALE_CASH_IN', 'Vente (encaissement)'), ('WIN_PAYOUT_CASH_OUT', 'Paiement gain (décaissement)'), ('WITHDRAWAL', 'Retrait caisse'), ('REPLENISH', 'Réapprovisionnement caisse'), ('ADJUSTMENT', 'Ajustment')], max_length=25),
        ),
    ]
