# Generated by Django 5.0.14 on 2026-05-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_portal', '0009_alter_agentcashboxentry_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketline',
            name='option',
            field=models.PositiveIntegerField(default=1, help_text='Option LOTO (1, 2, 3)'),
        ),
    ]
